//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConsoleTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDocumentsService")]
    public interface IDocumentsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/GetDocumentById", ReplyAction="http://tempuri.org/IDocumentsService/GetDocumentByIdResponse")]
        Database.Document GetDocumentById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/GetDocumentById", ReplyAction="http://tempuri.org/IDocumentsService/GetDocumentByIdResponse")]
        System.Threading.Tasks.Task<Database.Document> GetDocumentByIdAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/SaveDocument", ReplyAction="http://tempuri.org/IDocumentsService/SaveDocumentResponse")]
        int SaveDocument(Database.Document document, int candidateId, byte type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/SaveDocument", ReplyAction="http://tempuri.org/IDocumentsService/SaveDocumentResponse")]
        System.Threading.Tasks.Task<int> SaveDocumentAsync(Database.Document document, int candidateId, byte type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/DeleteDocumenyById", ReplyAction="http://tempuri.org/IDocumentsService/DeleteDocumenyByIdResponse")]
        void DeleteDocumenyById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/DeleteDocumenyById", ReplyAction="http://tempuri.org/IDocumentsService/DeleteDocumenyByIdResponse")]
        System.Threading.Tasks.Task DeleteDocumenyByIdAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentsServiceChannel : DatabaseConsoleTests.ServiceReference1.IDocumentsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentsServiceClient : System.ServiceModel.ClientBase<DatabaseConsoleTests.ServiceReference1.IDocumentsService>, DatabaseConsoleTests.ServiceReference1.IDocumentsService {
        
        public DocumentsServiceClient() {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Database.Document GetDocumentById(long id) {
            return base.Channel.GetDocumentById(id);
        }
        
        public System.Threading.Tasks.Task<Database.Document> GetDocumentByIdAsync(long id) {
            return base.Channel.GetDocumentByIdAsync(id);
        }
        
        public int SaveDocument(Database.Document document, int candidateId, byte type) {
            return base.Channel.SaveDocument(document, candidateId, type);
        }
        
        public System.Threading.Tasks.Task<int> SaveDocumentAsync(Database.Document document, int candidateId, byte type) {
            return base.Channel.SaveDocumentAsync(document, candidateId, type);
        }
        
        public void DeleteDocumenyById(long id) {
            base.Channel.DeleteDocumenyById(id);
        }
        
        public System.Threading.Tasks.Task DeleteDocumenyByIdAsync(long id) {
            return base.Channel.DeleteDocumenyByIdAsync(id);
        }
    }
}
