//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Document))]
    [KnownType(typeof(Evaluation))]
    [KnownType(typeof(RecruitmentStage))]
    [KnownType(typeof(Person))]
    [KnownType(typeof(Decision))]
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.Document = new HashSet<Document>();
            this.RecruitmentStage = new HashSet<RecruitmentStage>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    
    	[DataMember]
        public virtual ICollection<Document> Document { get; set; }
    	[DataMember]
        public virtual Evaluation Evaluation { get; set; }
    	[DataMember]
        public virtual ICollection<RecruitmentStage> RecruitmentStage { get; set; }
    	[DataMember]
        public virtual Person Person { get; set; }
    	[DataMember]
        public virtual Decision Decision { get; set; }
    }
}
