//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContainer : DbContext
    {
    	public DatabaseContainer()
            : this(false) { }
    
        public DatabaseContainer(bool proxyCreationEnabled)
            : base("name=DatabaseContainer")
        {
    						this.Configuration.LazyLoadingEnabled = false;
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public DatabaseContainer(string connectionString)
          : this(connectionString, false) { }
    	  
        public DatabaseContainer(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    						this.Configuration.LazyLoadingEnabled = false;
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Decision> Decisions { get; set; }
        public virtual DbSet<RecruitmentStage> RecruitmentStages { get; set; }
        public virtual DbSet<SoftSkill> SoftSkills { get; set; }
        public virtual DbSet<SoftSkillsEvaluation> SoftSkillsEvaluations { get; set; }
        public virtual DbSet<SkillsEvaluation> SkillsEvaluations { get; set; }
    }
}
