//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Candidate))]
    
    public partial class Decision
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public byte Type { get; set; }
    	[DataMember]
        public string Answer { get; set; }
    	[DataMember]
        public string Reason { get; set; }
    	[DataMember]
        public int CandidateId { get; set; }
    	[DataMember]
        public string Company { get; set; }
    
    	[DataMember]
        public virtual Candidate Candidate { get; set; }
    }
}
