//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    [KnownType(typeof(Candidate))]
    
    public partial class Person
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string SurName { get; set; }
    	[DataMember]
        public string Mail { get; set; }
    	[DataMember]
        public string Phone { get; set; }
    	[DataMember]
        public string Address { get; set; }
    	[DataMember]
        public string Pesel { get; set; }
    
    	[DataMember]
        public virtual User User { get; set; }
    	[DataMember]
        public virtual Candidate Candidate { get; set; }
    }
}
