//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Evaluation))]
    [KnownType(typeof(Skill))]
    
    public partial class SkillsEvaluation
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public byte Mark { get; set; }
    	[DataMember]
        public int EvaluationId { get; set; }
    	[DataMember]
        public int SkillId { get; set; }
    
    	[DataMember]
        public virtual Evaluation Evaluation { get; set; }
    	[DataMember]
        public virtual Skill Skill { get; set; }
    }
}
